[platformio]
src_dir = firmware/Growbox_CriticalKush_V6
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
lib_deps =
  tzapu/WiFiManager@^2.0.17
  ayushsharma82/ElegantOTA@^2.2.9
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.14
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^3.11.0
build_flags =
  -DELEGANTOTA_USE_ASYNC_WEBSERVER=0
